var easyBoard = Immutable.fromJS([
    [NONE, NONE, PIECE, PIECE, PIECE, NONE, NONE],
    [NONE, NONE, PIECE, PIECE, PIECE, NONE, NONE],
    [EMPTY, EMPTY, PIECE, PIECE, PIECE, EMPTY, EMPTY],
    [EMPTY, EMPTY, PIECE, EMPTY, PIECE, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
    [NONE, NONE, EMPTY, EMPTY, EMPTY, NONE, NONE],
    [NONE, NONE, EMPTY, EMPTY, EMPTY, NONE, NONE],
]);
var smallBoard = Immutable.fromJS([
    // [EMPTY, PIECE, PIECE]
    [PIECE, PIECE, EMPTY]
]);

[[NONE, NONE, EMPTY, EMPTY, EMPTY, NONE, NONE], [NONE, NONE, EMPTY, PIECE, EMPTY, NONE, NONE], [EMPTY, EMPTY, PIECE, PIECE, PIECE, EMPTY, EMPTY], [EMPTY, PIECE, PIECE, PIECE, PIECE, PIECE, EMPTY], [PIECE, PIECE, PIECE, PIECE, PIECE, PIECE, PIECE], [NONE, NONE, EMPTY, EMPTY, EMPTY, NONE, NONE], [NONE, NONE, EMPTY, EMPTY, EMPTY, NONE, NONE]] // 2-1
[[NONE, NONE, EMPTY, PIECE, EMPTY, NONE, NONE], [NONE, NONE, PIECE, PIECE, PIECE, NONE, NONE], [EMPTY, PIECE, PIECE, PIECE, PIECE, PIECE, EMPTY], [EMPTY, EMPTY, EMPTY, PIECE, EMPTY, EMPTY, EMPTY], [EMPTY, EMPTY, EMPTY, PIECE, EMPTY, EMPTY, EMPTY], [NONE, NONE, PIECE, PIECE, PIECE, NONE, NONE], [NONE, NONE, PIECE, PIECE, PIECE, NONE, NONE]] // 2-2
